version: "3.8"
x-common-variables: &common-variables
  MYSQL_DATABASE: phongtro
  MYSQL_USER: thanhtruong
  MYSQL_PASSWORD: truong911

services:
  mysql_db:
    platform: linux/x86_64
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: truong911
      MYSQL_HOST: localhost

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    links:
      - client:client
      - api:api

  api:
    image: thanhtruong869/api-phongtro-app:latest
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - mysql_db

  client:
    image: thanhtruong869/client-phongtro-app:latest
    restart: always
    depends_on:
      - api
    stdin_open: true
    ports:
      - 3000:3000
      
  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: truong911
volumes:
  db_data:
