// Use extension REST client: humao.rest-client

@port = 3030
@url = http://localhost

### Register
POST {{url}}:{{port}}/api/v1/auth/register
Content-Type: application/json

{
    "phone":"0938334123",
    "password":"truong123",
    "name":"truong"
}

### Login
POST {{url}}:{{port}}/api/v1/auth/login
Content-Type: application/json

{
   "phone":"0938134357",
    "password":"truong123"
}

### Insert
POST {{url}}:{{port}}/api/v1/insert

### Get user
GET {{url}}:{{port}}/api/v1/user/getUserCurrent
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmMGI2MzMxLTJiNGMtNDNlMC05ZjNhLWNjZjg0OWZhNGIzYSIsInBob25lIjoiMDkzODMzNDEyMyIsImlhdCI6MTY5MDk4MDUzNSwiZXhwIjoxNjkxMTUzMzM1fQ.jZoXbA6moOrV3e0g39qMG2HMxm5vCjS5XKSeXTQ2rn4


