name: Docker Image CI

on:
  push:
    branches: ['releases']
  pull_request:
    branches: ['releases']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yaml

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: List files in context
        run: ls

      - name: List files in context
        run: cd client

      - name: List files in context
        run: ls

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: /Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/v1

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest}}
