name: Docker Image CI

on:
  push:
    branches: ['releases']
  pull_request:
    branches: ['releases']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: thanhtruong869 # name of Docker Hub ID
      IMAGE_NAME: client-app
      IMAGE_TAG: v1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yaml

      - name: Build and run Docker Compose
        run: docker-compose build
      
      - name: Check images
        run: docker images
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push thanhtruong869/client-app:v1
        
      
