name: Docker Image CI

on:
  push:
    branches: ['releases']
  pull_request:
    branches: ['releases']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Change to client directory
        run: cd client
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
