name: Docker Image CI

on:
  push:
    branches: ['releases']
  pull_request:
    branches: ['releases']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yaml

      - name: Build and run Docker Compose
        run: docker-compose up -d
